@startuml
User -> Cache: Изменение статуса заказа
Cache --> MES_db: Изменение статуса заказа в базе данных
Cache --> MES_db: (*) Запрос списка актуальных заказов
MES_db --> Cache: Возврат списка актуальных заказов

User -> Cache: Получение списка заказов
Cache -> User: Возврат списка заказов
@enduml
